name: First GitHub Action   
on:
  push:
    branches:
      - Main
jobs:
    hello:
     runs-on: ubuntu-latest
     steps:
        - name: Print Message
          run: echo "My first GitHub Action is running!"    